### ISSUE TITLE
Warum in 20-tel Punkten?

### ISSUE THREAD

**Issue by icho-cds-vorlage** [icho-cds-vorlage/IChO-CDS-Vorlage#4]
Warum in 20-tel Punkten?

_Originally posted by @icho-cds-vorlage in https://github.com/icho-cds-vorlage/IChO-CDS-Vorlage/pull/3#discussion_r1830918879_

Es sollte eine Umfrage gemacht werden ob 20-tel Punkte erlaubt sein sollten. Momentanes Format sollte allerdings nicht verändert werden um die Vorlage nicht zu sehr in ursprünglicher abzuändern.

Schlage einen expunkte Command für genauere Punktevergabe in diesem Maße vor.

-Paul

**Comment by frederikz01** [comment]
Mir ist aufgefallen, dass bisher durch die Abschneidung der Nachkommastellen durch \xintNum die Kontrolle der Punktestückelung gänzlich umgangen war (einfach "falsche" Summe ohne Fehlermeldung). Dafür habe ich \punkte jetzt mit einer \xintifInt Prüfung versehen. Welche(s) Vielfache(s) ganzzahlig sein muss, ist damit unabhängig vom Multiplikator für den Counter wählbar. 

Ich verstehe nicht ganz, worauf du mit deinem Vorschlag hinauswillst.

**Comment by Electron4444** [comment]
Hat sich erledigt habe nur nicht ganz einsehen können, wie ich die Funktionen die Counter anpassen und was davor mit den Werten gemacht wurde. Passt so
